### ISSUE TITLE
前置已失效

### ISSUE THREAD

**Issue by defoliation1** [chimmhuang/GearInquirySystem#1]
失效的前置： com.github.pagehelper:pagehelper:pom:3.4.2-fix in central (https://repo.maven.apache.org/maven2)

如果可以的话，能不能补充下README

**Comment by chimmhuang** [comment]
> 失效的前置： com.github.pagehelper:pagehelper:pom:3.4.2-fix in central (https://repo.maven.apache.org/maven2)
> 
> 如果可以的话，能不能补充下README

哈哈哈，这是当年小弟的毕业设计了。。已经搁置了，，今天才发现，SQL都没有。都没法运行了
